<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>NeuroNotes.GitHub.UnitTests</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\GitHub\NeuroNotes.GitHub.Application\NeuroNotes.GitHub.Application.csproj" />
        <ProjectReference Include="..\..\src\GitHub\NeuroNotes.GitHub.Persistence\NeuroNotes.GitHub.Persistence.csproj" />
        <ProjectReference Include="..\..\src\GitHub\NeuroNotes.GitHub.Public\NeuroNotes.GitHub.Public.csproj" />
    </ItemGroup>

</Project>
