<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NeuroNotes.AiAssistant.Public\NeuroNotes.AiAssistant.Public.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.SemanticKernel" />
      <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" />
    </ItemGroup>

</Project>
