<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit.Abstractions" />
      <PackageReference Include="MassTransit.MessagePack" />
      <PackageReference Include="Telegram.Bot" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AiAssistant\NeuroNotes.AiAssistant.Public\NeuroNotes.AiAssistant.Public.csproj" />
      <ProjectReference Include="..\..\AudioProcessing\NeuroNotes.AudioProcessing.Public\NeuroNotes.AudioProcessing.Public.csproj" />
      <ProjectReference Include="..\..\GitHub\NeuroNotes.GitHub.Public\NeuroNotes.GitHub.Public.csproj" />
      <ProjectReference Include="..\..\Platform\NeuroNotes.Platform.Public\NeuroNotes.Platform.Public.csproj" />
      <ProjectReference Include="..\NeuroNotes.TelegramBot.Public\NeuroNotes.TelegramBot.Public.csproj" />
    </ItemGroup>

</Project>
