<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CaseConverter" />
      <PackageReference Include="MassTransit" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NeuroNotes.TelegramBot.Application\NeuroNotes.TelegramBot.Application.csproj" />
    </ItemGroup>

</Project>
