<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>948dae6b-c0c1-4a56-ac56-a3252336b6a8</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grafana.OpenTelemetry" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    </ItemGroup>

    <ItemGroup>
      <None Update="ggml-base.bin">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AiAssistant\NeuroNotes.AiAssistant.Application\NeuroNotes.AiAssistant.Application.csproj" />
      <ProjectReference Include="..\AiAssistant\NeuroNotes.AiAssistant.Infrastructure\NeuroNotes.AiAssistant.Infrastructure.csproj" />
      <ProjectReference Include="..\AiAssistant\NeuroNotes.AiAssistant.Public\NeuroNotes.AiAssistant.Public.csproj" />
      <ProjectReference Include="..\AudioProcessing\NeuroNotes.AudioProcessing.Infrastructure\NeuroNotes.AudioProcessing.Infrastructure.csproj" />
      <ProjectReference Include="..\AudioProcessing\NeuroNotes.AudioProcessing.Public\NeuroNotes.AudioProcessing.Public.csproj" />
      <ProjectReference Include="..\GitHub\NeuroNotes.GitHub.Infrastructure\NeuroNotes.GitHub.Infrastructure.csproj" />
      <ProjectReference Include="..\Platform\NeuroNotes.Platform.Application\NeuroNotes.Platform.Application.csproj" />
      <ProjectReference Include="..\Platform\NeuroNotes.Platform.Infrastructure\NeuroNotes.Platform.Infrastructure.csproj" />
      <ProjectReference Include="..\Platform\NeuroNotes.Platform.Public\NeuroNotes.Platform.Public.csproj" />
      <ProjectReference Include="..\TelegramBot\NeuroNotes.TelegramBot.Application\NeuroNotes.TelegramBot.Application.csproj" />
      <ProjectReference Include="..\TelegramBot\NeuroNotes.TelegramBot.Infrastructure\NeuroNotes.TelegramBot.Infrastructure.csproj" />
    </ItemGroup>

</Project>
