global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using NeuroNotes.TelegramBot.Persistence.Configurations;
global using NeuroNotes.TelegramBot.Persistence.Entities;
global using NeuroNotes.TelegramBot.Persistence.Repositories;
global using NeuroNotes.TelegramBot.Public;